{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.couchbase.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AGENTMEMORY_USERNAME: {{ .Values.couchbase.username | quote }}
  AGENTMEMORY_PASSWORD: {{ .Values.couchbase.password | quote }}
{{- end }}
